name: Local Docker Build

on:
  pull_request:
    branches:
      - development  

jobs:
  local-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        run: docker build -t local-test-image:latest .

      - name: Run Docker container locally
        run: |
          docker run -d --name local-test-container -p 8080:80 local-test-image:latest
          sleep 10  # Wait for container to initialize
          docker ps  # Verify the container is running

      - name: Run tests
        run: curl -f http://localhost:8080 

      - name: Clean up
        run: |
          docker stop local-test-container
          docker rm local-test-container
